# ArgoCD Application - Health Responder
# @author Shanaka Jayasundera - shanakaj@gmail.com
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-responder
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shanaka-versent/shanaka-aks-poc.git
    targetRevision: HEAD  # Automatically follows default branch
    path: kubernetes
    directory:
      include: "02-health-responder.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-health
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
